# Generated by Django 4.2.1 on 2023-05-09 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="guest_can_skip",
            new_name="votes_to_skip",
        ),
    ]
